### ISSUE TITLE
no report output

### ISSUE THREAD

**Issue by alejandrohagan** [loichyan/nerdfix#13]
Thank you for the package!

I'm using nerdfix on my popos linux system. I believe I am running it correctly and it appears to run correct (see message below) however it doesn't generate a report at all.

I am using:

```
nerdfix 0.3.1
cheat-sheet: b5bf856
```
What am I missing?
```
 nerdfix check -r R
```
Running the above generates the below output
```
 INFO nerdfix::runtime: Check input file 'R/utils-pipe.R'
 INFO nerdfix::runtime: Check input file 'R/contoso_dim_date.R'
 INFO nerdfix::runtime: Check input file 'R/contoso_dim_product.R'
 INFO nerdfix::runtime: Check input file 'R/contoso_dim_promotion.R'
 INFO nerdfix::runtime: Check input file R/contoso_dim_product_subcategory.R'
 INFO nerdfix::runtime: Check input file 'R/divide.R'
 INFO nerdfix::runtime: Check input file 'R/totalytd.R'
 INFO nerdfix::runtime: Check input file 'R/contoso_fact_sales.R'
 INFO nerdfix::runtime: Check input file 'R/contoso_dim_channel.R'
 INFO nerdfix::runtime: Check input file 'R/new_vs_returning.R'
 INFO nerdfix::runtime: Check input file 'R/abc.R'
 INFO nerdfix::runtime: Check input file 'R/count_plus.R'
 INFO nerdfix::runtime: Check input file 'R/show_in_excel.R'
 INFO nerdfix::runtime: Check input file 'R/time_intelligence.R'
 INFO nerdfix::runtime: Check input file 'R/datasets.R'
 INFO nerdfix::runtime: Check input file 'R/abc_graph.R'
 INFO nerdfix::runtime: Check input file 'R/calculate.R'
 INFO nerdfix::runtime: Check input file 'R/clean_file_names.R'
 INFO nerdfix::runtime: Check input file 'R/make_segmentation.R'

```
but then I'm returned to my command  prompt without any additional outputs

Thoughts?

**Comment by loichyan** [comment]
Possibly there are no obsolete icons in these files?

**Comment by alejandrohagan** [comment]
When I go to the nerd font and search for R related icons -- I can see they have a few options. Am I misunderstanding the intention of the nerdfix?

**Comment by loichyan** [comment]
`nerdfix` is used to replace obsolete icons since [Nerd Font v2.3.3](https://github.com/ryanoasis/nerd-fonts/releases/tag/v2.3.3) with new ones. Are you looking to list all the icons used in these files? If so, I would add a new feature in the next release to accomplish this.

**Comment by alejandrohagan** [comment]
hi!
First thank you for thepackage. I'm a biginner with linux and getting my skill sets up the learning curve so I apologize if my questions are amatuerish.

What I'm intending to do is that when I look at R files (files with extension .R) they have an icon that is more familiar to me (say the R logo which is available on nerdfont) similar to how when I look at folder -- I see a folder icon.

Currently when I look at R file I get a symbol but its not a recognizable to me. I wanted to use your package to identify those symbols and then input the replacement symbol.

Is my understanding of your package correct?

**Comment by loichyan** [comment]
Never mind!

The purpose of `nerdfix` is to help you migrate to Nerd Fonts releases after v3.0.0. For example, the icon for R language is " 󰟔 " in v3, but " ﳒ " in v2 (except v2.3.3, which contains both  new and obsolete icons), and the latter one should be unrecognizable if you are using Nerd Fonts v3, as I've seen on my machine:

![image](https://github.com/loichyan/nerdfix/assets/73006950/aa162ce6-3e32-40c2-b7f4-fd1d655f39a6)

Otherwise, the former might be unrecognizable if you are using older releases of Nerd Fonts.

In your case, I guess that you are using some TUI apps (i.e., run from a **T**erminal with an **U**ser **I**nterface), such as (Neo)Vim. If so, you would need to check the configuration files and plugins of these apps to find where they actually set the icon for R files (as well as for other language files, folders, etc.).

**Comment by alejandrohagan** [comment]
thank you!! appreciate your response
